name = "RingelN5K11P6"
version = "0.1.0"
defaultTargets = ["RingelN5K11P6"]
[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "17b4b96c4eb874624e9cab005e966a25fd68ab14"
[[lean_lib]]
name = "RingelN5K11P6"
srcDir = "formal"
