name = "KotzigT12K25"
version = "0.1.0"
defaultTargets = ["KotzigT12K25"]
[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "17b4b96c4eb874624e9cab005e966a25fd68ab14"
[[lean_lib]]
name = "KotzigT12K25"
srcDir = "formal"
