name = "RingelN6K13P7"
version = "0.1.0"
defaultTargets = ["RingelN6K13P7"]
[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "17b4b96c4eb874624e9cab005e966a25fd68ab14"
[[lean_lib]]
name = "RingelN6K13P7"
srcDir = "formal"
